[package]
name = "coc-assets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
zstd.workspace = true
astc-decode = "0.3"
png = "0.17"

[[example]]
name = "sprites"
path = "examples/sprites.rs"

[[example]]
name = "sctx2png"
path = "examples/sctx2png.rs"

[lints]
workspace = true
